### ISSUE TITLE
Construct File objects with a buffer

### ISSUE THREAD

**Issue by hobu** [laspy/laspy#102]
@grantbrown What is likely the most convenient modifications for me to make to allow the construction of File objects using a mmap or numpy array of the entire contents of the file directly? I am currently writing a Python library for [Entwine Point Tile](https://entwine.io/entwine-point-tile.html), and I already have the file in memory once fetched. It would be nice to avoid i/o'ing to a file just to use the laspy interface.

**Comment by grantbrown** [comment]
Hmm, that's a good question. Unsurprisingly, there are some "design" issues (more like the lack thereof!). In particular, there's far too much reaching into the DataProvider to get low-level attributes throughout the code, so whatever you do will have to either overhaul all that nonsense or appropriately generate the same object state one would obtain by reading it from a file.

I think I'd take one of two approaches:

1. Modify File.__init__ and File.open methods to generalize them to handle an existing mmap, then follow the calls into base to make sure anything which needs it gets updated. This might be the most straightforward, since mmap already behaves like a file. 
2. Create a "from_<whatever>" method on File. This is more general, but to get it to work with numpy arrays might be a little tricky

I assume this is really only for read mode?

**Comment by hobu** [comment]
https://github.com/davidcaron/laspy/commit/dd5d09b28e3e26265ffa38f9b592852b89a968c9 implements it.
