### ISSUE TITLE
Laspy writer dtype vs data_type

### ISSUE THREAD

**Issue by pepijntje02** [laspy/laspy#139]
Hello,

I am trying to write my points to a LAS file. At the moment I read a lasfile, change the points and use some filters from for example PDAL. After that I am left with a structured Numpy array. I want to export a new LAS file and add the new points. 

It think that it is easier to explain with parts of my code.

First the LAS file is loaded in the `cloud` variable.
```python
cloud = laspy.file.File('filename.las')

In [47]: cloud.points.dtype
Out[47]: dtype([('point', [('X', '<i4'), ('Y', '<i4'), ('Z', '<i4'), ('intensity', '<u2'), ('flag_byte', 'u1'), ('raw_classification', 'u1'), ('scan_angle_rank', 'i1'), ('user_data', 'u1'), ('pt_src_id', '<u2'), ('gps_time', '<f8'), ('red', '<u2'), ('green', '<u2'), ('blue', '<u2')])])
```
Now I will use some filters, but the result is an array like this:
```python
In [51]: array.dtype
Out[51]: dtype([('X', '<f8'), ('Y', '<f8'), ('Z', '<f8'), ('Intensity', '<u2'), ('flag_byte', 'u1'), ('raw_classification', 'u1'), ('scan_angle_rank', 'i1'), ('user_data', 'u1'), ('pt_src_id', '<u2'), ('gps_time', '<f8'), ('Red', '<u2'), ('Green', '<u2'), ('Blue', '<u2'), ('Classification', 'u1'), ('ClusterID', '<i8')])
```
The dtype is not everywhere the same as the first dtype (from the source file). Also there are two new columns, `('Classification', 'u1')` and  `('ClusterID', '<i8')`.
So I manipulate the dtype, thereafter the dtype of the same columns (like `'X'`) are equal and I set the dtype for the Classification to `int32` because it does not need to be too large.

```python
def change_dtype(oldtype, newtype):
    dt = []
    oldtypenames = list(map(str.lower, oldtype.names))
    for name in newtype.names:
        if name.lower() in oldtypenames:
            idx = oldtypenames.index(name.lower())
            dt.append((name, oldtype[idx]))
        else:
            if name == 'ClusterID':
                dt.append((name, '<i4'))
            else:
                dt.append((name, newtype[name]))
    return dt

oldtype = cloud.points['point'].dtype
newtype = array.dtype
array = np.array(array, dtype=change_dtype(oldtype, newtype)
```
Thereafter I add the `point` dtype to the array so the dtypes are (almost) equal:
```python
 array= np.array(list(zip(array)), np.dtype([('point', array.dtype)]))  
In [64]: array.dtype
Out[64]: dtype([('point', [('X', '<i4'), ('Y', '<i4'), ('Z', '<i4'), ('Intensity', '<u2'), ('flag_byte', 'u1'), ('raw_classification', 'u1'), ('scan_angle_rank', 'i1'), ('user_data', 'u1'), ('pt_src_id', '<u2'), ('gps_time', '<f8'), ('Red', '<u2'), ('Green', '<u2'), ('Blue', '<u2'), ('Classification', 'u1'), ('ClusterID', '<i4')])])
```
So here comes the "tricky" part. I have to store this new array in the new LAS file. First I open a new file and define the header, based on the header of the source file. Then I change some parts of the header so the size and dimensions are equal to the new array.

_This is the part where I can use some help:_
```python
outFile = laspy.file.File("output.las", mode='w', header=cloud.header)
# Change number of point in lasfile for new array:
outFile.header.count = len(array)
#check which types are already defined in the new output file:
exisiting_types = [f.name.lower() for f in outFile.point_format]
# check which names are in the array but not in the output file:
for name in [n for n in array.dtype.names if n.lower() not in exisiting_types]:
    # In this case the only new ones are "Classification" and ClusterID
    outFile.define_new_dimension(name=name, data_type=4,
            description="Description from pdal")
```
I wanted to use the dtype from `Classification` of `ClusterID` for the data_type, but how the datatypes are defined is a mystery for me. This works, but I am wondering if it is possible to choose the data_type based on the array.

The last part of the code is as follow (and works when then new dimensions are added):
```python
outFile.points = array
outFile.close()
```

In this case the `data_type=4` is equal to `short`[1] and `int16`. So for now it works fine, but when the datatype changes due to different filters or other manipulations of the array (or points) it would be nice to use the known data type from the input array which is used as input for the points.

If you can clarify how to choose  which data_type for a new dimension that would be very helpful. 

Kind regards,
Pepijn

[1] https://laspy.readthedocs.io/en/latest/tut_part_3.html

**Comment by grantbrown** [comment]
I'm not following 100%, in part because I think you're directly interfacing with some more "internal" parts of laspy. That's not inherently bad (I can see where you'd save a lot of overhead), but it means you need to be pretty careful. Specifically, unless I'm forgetting something, directly interfacing with the dtypes for point records wasn't an anticipated use. There's a whole set of abstractions with point_format that could be broken if you do that (not to  mention breaking the las specification if you do things like modify the binary format of something defined in the spec). 

To answer your direct question, I think all you need to do is have a set of lookup rules to match the Python data type you have in your array to one of the numeric codes (0-30) given in the table you linked. That will depend on what kind of data you have and it's magnitude/length. For example, if you have something that is a floating point in Python you'd probably select data_type=9 or 10, for float/double. If you have string data, there's not a super great fit defined in the specification if it's longer than a few characters. Either way, you'll need to come up with some logic mapping the data you observe to one of the numeric codes. 

Does that help?

**Comment by pepijntje02** [comment]
Hi,

Thanks for your replay. I was not aware that I was working with the "internal" parts of laspy, it is gone this way during debugging of the code. The reason is that I got errors if I did not set the header and dtypes correct. 

Can you direct me to (or give my advise) documentation about writing points to las files? All I can find in the documentation is about the manipulation of the points, on the same las-file. But in my case I am trying to store an array of points in the las-file. 

For exmaple: 
```python
array = #numpy array containing the points (and other fields like classification etc.)
outFile = laspy.file.File('filename.las', mode='w', header=inFile.header)
outFile.points = array
>>> ValueError: structures must have the same size
```
When I check the `outFile.points` I can see that it is already filled with zeros. 

So is there a better/cleaner way to manipulate the lasfile data?

Another example where I get confused by laspy is:

```python
inFile = laspy.file.File('filename.las', mode='wr')
inFile.header.system_id = "here i want laspy"
>>> LaspyException: Fields must be replaced with data of the same length. system_id should be length 32, received 17
```

I get the feeling that I do not fully understand the methods how laspy interacts with the las file. Is there a method how to tackle this, or is this just not the purpose of the laspy module?

But for now I will use this method, until I find the way how was intended to work.

**Comment by grantbrown** [comment]
Laspy is written directly against the binary specifications of the las formats, so all of the interfaces are designed around preserving that format. The most "laspy" way to do what you're trying to do is to use the dimension interfaces and set data by dimension, rather than directly doing so using the full points array (at least until you can be sure you'll produce exactly the correct points array). Here's an example of creating a las file from scratch and putting some data in it:

```
from laspy import header, file
import numpy as np



# Create some float data
points3d = np.random.rand(1000, 3)


h = header.Header(file_version=1.4,
                  point_format=10)
h.x_scale = 0.001
h.y_scale = 0.001
h.z_scale = 0.001

f = file.File("test.las", mode = "w", header = h)
# Set the scaled points
f.x = points3d[:,0]
f.y = points3d[:,1]
f.z = points3d[:,2]
f.close()

# Create some int data
points3d_int = (points3d/h.x_scale).round()

f2 = file.File("test2.las", mode = "w", header = h)
# Set the scaled points
f2.X = points3d_int[:,0]
f2.Y = points3d_int[:,1]
f2.Z = points3d_int[:,2]
f2.close()

```

A couple of things to note:

1. f and f2 above are exactly identical. That's because the las format does not natively store floating point dimension data, it stores things as integers with a scale and offset. The dimensions X, Y, and Z store integers (accessed via properties on the File object), and the dimensions x,y, and z are simply an interface to that integer backend. Depending on the scale of your data, you may need to tweak the scale/offset for maximum precision. 
2. When you're setting dimensions in this way, you're really just using properties which call getters and setters to properly populate the file. The first time dimenional data is written to a las file, the whole file is padded out and many header attributes are set to make sure the file remains valid and in compliance with the specification. 

In your case, you should be able to:

1. Create the file as above
2. Use the tools you're already familiar with to create new dimension (those not captured in the point_format you choose)
3. Use the properties on the File object to populate your dimensions. 

If you want to do this more efficiently, you can directly supply the points, but you'll need to make sure you have the binary format correct. Working with the individual dimensions first will help you get examples to match. 

Your second question is related, and the error you're receiving is clear - laspy is expecting 32 bytes of data for the system_id field, because that's what the specification requires. Your string is only length 17, so laspy complains. The typical solution would be to pad this with null bytes:

```
f.header.system_id = "\0"*27 + "laspy"
```

**Comment by pepijntje02** [comment]
Hi,

Sorry for this extremely late response, but what you write here is clear and a better approach.
