### ISSUE TITLE
pylas -> laspy ?

### ISSUE THREAD

**Issue by tmontaigu** [laspy/laspy#142]
#141 talks about  "refactoring laspy's internals to match what he has been done with pylas".

Refactoring laspy, as in, doing a succession of  step by step changes is still not possible, so the only option, really, would be to , move the code from pylas's repo to laspy's repo and decide what parts of the laspy API behaviour should be
kept (or try to) and what part can be changed and call it laspy 2.0 ?

Because, obviously even though pylas's API is close to laspy in some aspects (accessing fields/dimension like classification, X, Y, Z, etc) there are other aspects that are not compatible (almost anything that is not field access, like the concept of laspy.File with modes).

**Comment by hobu** [comment]
In my opinion, the important API bits are the field getting/setting and access methods around data. That's where people have the most code that's intricately linked to laspy. The old-style per-point libLAS API method maybe still has some users, but I think you could ditch them because that API existed before numpy became the preferred way to interact with this kind of data. People just want the fastest and most convenient route to get from LAS/LAZ -> numpy and numpy -> LAS/LAZ.

I think laspy's File stuff should be ditched entirely. It isn't aligned with Python's file behavior. Headers that are free standing vs. those that are tied to a file has very confusing behavior.  

laspy's Header behavior is really confusing because it has behavior attached to File modes. This should be refactored entirely so it behaves the same regardless of something being read or written. 

laspy doesn't play well with the standard logging facilities of Python (which didn't exist in their current form when laspy was first written).

**Comment by tmontaigu** [comment]
> The old-style per-point libLAS API method maybe still has some users, but I think you could ditch them

It should be ditched because it is a rather ineficient and not very Pythonic way to manipulate points.
pylas 1.0 was goind to introduce 'chunked' read/write to still have to possibility to process files that are to big to fit in memory.

> I think laspy's File stuff should be ditched entirely. It isn't aligned with Python's file behavior.

I agree

> laspy's Header behavior is really confusing because it has behavior attached to File modes. This should be refactored entirely so it behaves the same regardless of something being read or written.

Regarding modes and files, this is the biggest difference between pylas and laspy.

In laspy,  the `File` is a memory map, this works well for LAS  (but complicates some parts of the implementation like adding vlrs, inserting points) but mmap does not work at all for LAZ since the data is compressed, so laspy uses a FakeMMAp which holds the uncompressed points which makes the behaviour sort of inconsistant betweenn LAS and LAZ.

In pylas, a typical script reads the LAS/LAZ file using `pylas.read`, it returns a `LasData` object which users use to access to the header, the vlrs , evlrs and points. All of this data is held in memory (ie not mmaped). 
And instead of `closing` the `File` the data, has to be saved using `.write` method

The API for the field access of the `LasData` object is already the same (or very close) to `laspy` and for `header` and `vlrs` i'm not really sure, they shouln't be far. 

More advanced script can open files in `r` (read only the header and/or do chunked reading) or `w` (as another way to create a new file, like to create a script that can split big files into smaller ones) or `a` (to append points to an existing file) modes

**Comment by hobu** [comment]
> It should be ditched because it is a rather ineficient and not very Pythonic way to manipulate points.
pylas 1.0 was goind to introduce 'chunked' read/write to still have to possibility to process files that are to big to fit in memory.

👍 to ditching it from me. People can always pin to older versions if they needed it.

> In pylas, a typical script reads the LAS/LAZ file using pylas.read, it returns a LasData object which users use to access to the header, the vlrs , evlrs and points. All of this data is held in memory (ie not mmaped).
And instead of closing the File the data, has to be saved using .write method

laspy's mmap approach comes from a time before Python had the buffer protocol. The old libLAS API supported streaming, so a goal of laspy was to preserve that, but in the end it doesn't seem worth the cost. If you're in Python, you're not here for memory efficiency and function call overhead. You're here to get the data as fast as you can to and from numpy.

**Comment by tmontaigu** [comment]
I started replacing laspy code with pylas code,

The Header and VLRs classes are different, but adapting to the changes should not be hard

laspy.File being gone is a rather big change from laspy 1.x.
   
    It means that reading, creating, saving/writing is done differently
   
An internal mapping is kept to translate some laspy dimension names which where not the same as pylas (eg `pt_src_id` -> `point_source_id`)

All the `get_*` like `get_classification`, `get_x` are gone, as well as `set_dimension`

The API to define extra dimension is not the same, maybe its possible to keep the backward compatibility
by keeping a `define_new_dimension` function that would just call the new one.

laspy supported python 2.6+ & 3.5+, now it would only support 3.6+

laspy supported filed 1.0 to 1.4, now it would support 1.2 to 1.4

**Comment by hobu** [comment]
> laspy supported filed 1.0 to 1.4, now it would support 1.2 to 1.4

Of all this consequences you posted, this is the only one that gives me much cause for concern. The ability to write valid 1.0 data is maybe not so important, but 1.1 is often used as a 'bare minimum' version in data warehousing scenarios. How hard might it be to reach back and get support for that?

Python 3.6+ support would be just fine with me. People can always go pin to older versions. We don't have to have the responsibility to support twenty years of Python versions.

Some dummy class for File that gives the user an error with a prescription what to do when they try to instantiate it would be quite useful.

**Comment by tmontaigu** [comment]
>  How hard might it be to reach back and get support for that?

Looking at the spec, it should not be too hard, as there doesn't seem to be much change from 1.1 to 1.2

On the other hand, there is no test for 1.0 and 1.1 files in the current repo 😛 

> Some dummy class for File that gives the user an error with a prescription what to do when they try to instantiate it would be quite useful.

Could probably be a good idea, there will also be a need for a migration/updating guide

**Comment by tmontaigu** [comment]
Also, laspy has some tools (in  the misc folder) should they be kept (and updated) ?

**Comment by hobu** [comment]
> Also, laspy has some tools (in the misc folder) should they be kept (and updated) ?

I think they can be ditched. @kbevers and @grantbrown?

**Comment by tmontaigu** [comment]
Closed by #143
