### ISSUE TITLE
unanticipated behavior for `LasData`'s  `__getitem__` method   

### ISSUE THREAD

**Issue by spolloni** [laspy/laspy#173]
*Total laspy newbie here* , but I was a bit surprised by the behavior of `LasData.__getattr__()` given my guess is it's trying to have a numpy indexing "feel".  My prior was that the method would return an object of the exact same type, rather than a `PackedPointRecords` instance.  

I tried changing this line:
https://github.com/laspy/laspy/blob/dfe83eb39b746f7d7927f9dc6a510b41a9799a6e/laspy/lasdata.py#L260

to:
```
self.points = self.points[item] 
return self
```

but it not so surprisingly broke a million tests. 

Just curious about the rationale behind this implementation...

**Comment by tmontaigu** [comment]
Why do you want to change `LasData._-getattr__` ?

The goal of this function is not to provide numpy indexing, but as its explained in its docstring, it is there to allow user to get access to as las dimension/ field by doing `las.fieldname` like `las.classification` (because if you look closely there is no `classification` attribute on LasData

**Comment by spolloni** [comment]
> The goal of this function is not to provide numpy indexing, but as its explained in its docstring, it is there to allow user to get access to as las dimension/ field

Thanks. I guess my first impression was that it's odd to allow users do things like `las[:100]` and `las[boolean_mask]` but to return a different object type than the object being indexed or sliced. 

I now understand that what I should really be doing is `las.points[:100]` and `las.points[boolean_mask]` instead, but I was in a situation where I wanted to sequentially perform several indexing and slicing operation on the points (basically just filtering down based on various criterias),  and found myself restricted by the inability to access the **scaled** points, given that `PackedPointRecords` doesn't have `x`, `y` and `z` properties. 

Is the change of `LasData.__getattr__` I'm proposing above problematic in a very fundamental way?

**Comment by tmontaigu** [comment]
> Is the change of LasData.__getattr__ I'm proposing above problematic in a very fundamental way?

Yes extremely problematic since when you do `las[something]` its not `LasData.___getattr__`  that gets called, its
`LasData.__getitem__`. And it is also no a correct implementation of `LasData.__getitem`.

At least now I see where your problem is 'unanticipated behavior', its is in `LasData.__getitem__`

**Comment by spolloni** [comment]
> its not `LasData.___getattr__` that gets called, its `LasData.__getitem__`

Ah yes, my bad and sorry for the confusion. Thanks for the PR -- I now see how returning a copy of the indexed/sliced `self` is crucial.
