### ISSUE TITLE
UnicodeDecodeError when trying to read a LAS file

### ISSUE THREAD

**Issue by Va2sili** [laspy/laspy#214]
Hi, I am trying to read a las file but I get the following error when running `laspy.open` function:
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xea in position 0: invalid continuation byte`

I think this is due to my LAS files having a too high version (2.0). Is there a way I can still read them using this library?
Thanks for your help.

**Comment by tmontaigu** [comment]
Lidar LAS format which this library is for, does not have a version 2.0.

So if your file has a version 2.0 then its likely not a LAS lidar but some other format (maybe Log Ascii Standard ?)

**Comment by Va2sili** [comment]
Thank you for your quick answer.
Yes it is a LAS file but I found out it has been produced by a Pavemetrics system, and Pavemetrics use their own version of LAS file, called "2.0" and this version is a proprietary format. So I can only open it with special software.

**Comment by tmontaigu** [comment]
Are you able to share a sample of the file?

But note that this library is for Standard LAS file, so if the file is truly not standard then I won't even try to make it work

**Comment by hobu** [comment]
There was some software that wrote LAS 2.0 files during the period where it looked like there was going to be a LAS 2.0. That never officially happened, but there is some content out there. github.com/hobuinc/ has a closed-source PDAL driver to extricate data from these if it is important, but we never released it due to not wanting to support it.
