### ISSUE TITLE
Classification in laspy doesn't match with lasinfo

### ISSUE THREAD

**Issue by Stakhan** [laspy/laspy#275]
On a specific file, I'm not able to retrieve classification values using laspy (getting an array full of 0 instead) even though the file seem to indeed be classified according to other software handling las files (lasinfo, displaz, TerraScan, ...).

Using laspy (v2.4.0):
```python
>>> import laspy
>>> import numpy as np
>>> las = laspy.read('test.laz')
>>> np.unique(las.classification)
array([0], dtype=uint8)
```

Using lasinfo:
```
histogram of classification of points:
          159000  unclassified (1)
        67533041  ground (2)
        14027066  water (9)
```
Here is the file in question: [https://we.tl/t-WIGOiZZt91](https://we.tl/t-WIGOiZZt91?utm_campaign=TRN_TDL_05&utm_source=sendgrid&utm_medium=email&trk=TRN_TDL_05) 
> NB: sorry for the big size (~405MB), I tried to extract a chunk of this file to send something smaller, but the problem would not be reproducible anymore

**Comment by tmontaigu** [comment]
It seems that its a problem with the laszip backend I can reproduce with laszip, but with lazrs I can't

**Comment by tmontaigu** [comment]
It happends only with this file ?

**Comment by tmontaigu** [comment]
Ok, I found the problem, basically, the file problem comes from the fact that the file is quite big
- 405MB of LAZ: 81_719_107 points of 34 bytes each so 2_778_449_638 bytes (2.147483647 GB)

The internal buffer used to  get the uncompressed bytes given by laszip uses an 32bit signed int to count the
number of bytes however (81_719_107 * 34) >= int32_max, which made the buffer 'stop' and only output 0s.

When using chunking, since after reading each chunk, that buffer gets emptied you don't reach the int32 limit
and the file is read correctly. (unless you try to read 63_161_284 which makes you go over the limit)

I have a fix locally for this, which allows to `laspy.read` the whole file and
get the expected result.

It will require a new version of the laszip-python backend

**Comment by tmontaigu** [comment]
a new release of laszip-python is available which fixes the problem

**Comment by Stakhan** [comment]
Thank you very much!
I can report that it works on my side with the new release (v0.2.3)
