### ISSUE TITLE
python mmap limits file size on 32 bit machines

### ISSUE THREAD

**Issue by grantbrown** [laspy/laspy#3]
Large (>1-3 GB) las files fail to open with 32 bit python. 

Current workaround is to use 64 bit python, along with the appropriate 64 bit numpy.

**Comment by umbe1987** [comment]
This is actually a limitation from my personal side as I (unlikely) have to stick with 32bit version of Python. Is there any possibility to (e.g.) read the LAS in chunks so that this issue might be somehow solverd? Thanks in advance!

**Comment by grantbrown** [comment]
Are you working in an embedded environment? Otherwise, processing large amounts of LIDAR data on a 32 bit machine sounds like a recipe for pain. 

It is possible to add a layer of abstraction which would permit the data to be read in chunks, but it would be tough to do without adding significant overhead. There's also an upper limit on the usefulness of such a scheme to process real data, since RAM is limited on 32 bit machines as well.

**Comment by umbe1987** [comment]
You're totally right. I was forced to use a 32bit python because it was embedded into ArcMap application. My workaround was to install the davidcaron fork (python3 branch) of laspy to be able to use laspy along with the arcpy module, which is also present in ArcGIS Pro installation, it is 64bit, but it is (what a shame) version 3.5 and thus not compatible with the official release of laspy. However, this temporarily workaround did solve my issue, and I am able to use laspy with Python 3.5 and arcpy now. I've already wrote something in this issue about this (#40). Thanks for the response!

**Comment by tmontaigu** [comment]
Closing as 32bit Python is not the norm.
laspy 2.0 will not use mmap and adds ability to read las in chunks
