### ISSUE TITLE
Reading extrabyte attribute 

### ISSUE THREAD

**Issue by alexguyot** [laspy/laspy#53]
Hi,

Sorry if I'm not posting into the right place.
I need to access values stored in the extrabyte area of my LiDAR points.
I can't find out how to do this with laspy ?

Any idea ?

Thanks a lot,
Alex

**Comment by Ellon** [comment]
Late reply, may still be useful.

(Disclaimer: I'm no laspy expert. I started using it few days ago). 

If I understood properly, the values stored into EXTRA BYTES are decoded from the VLR and made accessible through their name. For instance, an extra bytes value with name "Amplitude" would be available through inFile.amplitude. 

To the extent of my current knowledge, I don't know if there is a easy way print the name of the extra bytes you have. What you can do is to find the VLR containing the extra bytes and look for names in VLR_body. For example, in the output generated by the following code:

```
>>> for (i, vlr) in enumerate(inFile.header.vlrs):
...     print i, vlr.user_id, vlr.record_id
... 
0 LASF_Projection 34735
1 LASF_Projection 34736
2 LASF_Projection 34737
3 LASF_Projection 2112
4 LASF_Spec 4
```
you're looking for the line with **LASF_Spec 4**, since this is the combination of User Id and Record Id that define the extra bytes VLR. In this example it is located at the VLR with index 4. Then you can do:
```
>>> extra_bytes_vlr = inFile.header.vlrs[4]
>>> extra_bytes_vlr.VLR_body
```
to visualize the whole extra bytes VLR body. You may get something like:
<pre>
"\x00\x00\x03\x0e<b>Amplitude</b>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x10'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
0\x00\x00\x00\x00\x00\x00\x00{\x14\xaeG\xe1z\x84?\x00\x00\x00\x00\x00\x00\x00\
x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00Echo signal amplitude [dB
]\x00\x00\x00\x00\x00\x00\x00\x00\x04\x0e<b>Reflectance</b>\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00x\xec\xff\xff\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x0
0\x00\x00\x00\x00\x00\x00\x00\x98:\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00{\x14\xaeG\xe1z\x84?\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00Echo signa
l reflectance [dB]\x00\x00\x00\x00\x00\x00\x03\x07<b>Deviation</b>\x00\x00\x00\x00\x0
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\
x00\x00\x00\xff\xff\xff\xff\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x0
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\
x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\x7f\x00\x00\x00\x00\x00\x0
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\
x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\
x00\x00\x00\x00\x00\x00Pulse shape deviation\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00"
</pre>
where you should look for the names like the ones in **bold**. The other text is the extra byte description. Names come before descriptions, and normally it should be clear what which one is what. You can access the extra bytes using the names, in lower case, without `\x00`s and with spaces replaced by `_`s, as it is done [in laspy/header.py, line 470](https://github.com/laspy/laspy/blob/b3091a274f9b3a3189dbe563d43634e6ed75d571/laspy/header.py#L470). In this example, it would be:
```
>>> inFile.amplitude
array([ 445,  146,  968, ...,  992, 1007,  942], dtype=uint16)
>>> inFile.reflectance
array([-1268, -1567,  -856, ...,  -593,  -578,  -642], dtype=int16)
>>> inFile.deviation
array([ 8,  0,  3, ..., 43, 54, 41], dtype=uint16)
```

Anyway, this depends on the names given for your extra bytes values. If they're not set or properly parsed then I don't know how to access them. Maybe a developer/maintainer may tell you an easier way to access the values and value names.

I hope this helps!
