### ISSUE TITLE
EXTRA BYTES: Scale, offset, raw values and data types

### ISSUE THREAD

**Issue by Ellon** [laspy/laspy#64]
I'm reading a LAS file with some EXTRA BYTES and I noticed that accessing them with `inFile.<extrabytesvaluename>` (lower-case) returns the raw value arrays. The [LAS Specification 1.4](http://www.asprs.org/wp-content/uploads/2010/12/LAS_1_4_r13.pdf) pages 24-26, describes the format of the EXTRA BYTES VLR, and it mention that they may have associated scales and offsets, controlled by the `options` field inside the VLR (see Table 25), and that the type is controlled by the `data_type` field (see Table 24).

So, to be coherent with the rest of the package, I think the raw values should be accessed using `inFile.<Extrabytesvaluename>` (captioned) and the scaled value with offset applied should be available through `inFile.<extrabytesvaluename>` according with the controlling bits set in the `option` field (like it is done with `inFile.X` and `inFile.x`). The correct type can also be deduced from the `data_type` fields (chars, ints, floats, up to vectors of size 3), returning the appropriate vector.

Do you plan to implement this idea anytime soon? If someone give me some pointers to where to start I can try to adapt the code to handle the EXTRA BYTES in the way I described here.

**Comment by forkozi** [comment]
I like the consistency idea.  I'm playing around with adding scaled extra bytes to las files, and I'm wondering if you've discovered any solutions or pointers since this post.  I've been able to write extra dimension data and the associated VLR (including the scale) to a las file, but I haven't been able to figure out how to read the scale from the VLR or apply it to the raw values in the extra dimension.
