### ISSUE TITLE
No module named glviewer

### ISSUE THREAD

**Issue by pooluut** [laspy/laspy#70]
When I run:

```
$ lasviewer file.las
```

Errors comes:
```
Something went wrong: 
No module named glviewer
```

**Comment by grantbrown** [comment]
If you want to visualize point clouds, you're probably better off with something more actively maintained: [http://speck.ly/](http://speck.ly/) - the visualization features of laspy are more of a "proof-of-concept" than anything else.

Nevertheless, I believe the issue should be fixed in [this commit](https://github.com/laspy/laspy/commit/b02b40900b5620972930cd0c201b4db1a6a69754).
